config/routes.rb
Rails.application.routes.draw do

  telegram_webhook BotRouter

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, :controllers => {
    :omniauth_callbacks => "auth"
  }

  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :signin_path
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :signout_path
  end

  #resources :challenges
  #match '/auth/:provider/callback', :to => 'auth#callback', :via => [:get, :post]

  authenticated :user do
    root 'home#index', as: 'authenticated_root'
  end
  devise_scope :user do
    root 'devise/sessions#new'
  end

  # Wrong route workaround
  match "/404", to: "errors#page_not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  match "*path", to: "errors#page_not_found", via: :all
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :omniauthable, :omniauth_providers => [:telegram]
  include ActionView::Helpers::DateHelper
  include Exlogger

  has_many :posts, dependent: :nullify
  has_many :rates, through: :posts
  has_many :challenges, dependent: :nullify

  before_save :log_info
  after_save :log_error
  after_create :log_info

  attr_accessor :email, :password
  attr_writer :login

  def login
    @login ||= self.uid
  end

  validates :uid, presence: true
  validates :credit, numericality: { greater_than_or_equal_to: 0 }
  #validates :password, presence: true, length: { in: 6..20 }, confirmation: true

  scope :best, -> {
    where(training_finished: true)
    .where(User.arel_table[:blocked_until].lt(Time.current))
    .order(rating: :desc)
  }

  def training?
    !training_finished
  end

  def namelink
    firstname.nil? ? "@#{username}" : "<a href=\"tg://user?id=#{uid}\">#{fullname}</a>"
  end

  def fullname
    "#{firstname} #{lastname}".strip
  end

  def block!(period)
    self.blocked_until = Time.current + period if self.blocked_until < Time.current + period
    self.challenges.map { |c| c.delete! }
    save
  end

  def blocked?
    blocked_until > Time.current if blocked_until
  end

  def rating_with_icon
    I18n.t('items.rating') + ' ' + rating.to_s
  end

  def credit_with_icon
    I18n.t('items.credit') + ' ' + credit.to_s
  end

  def header(item)
    item + I18n.t('menu.header', rating: rating, credit: credit) + "\n"
  end

  def degrade!
    self.rating = 0
    self.rating_position = nil
    self.rating_position_old = nil
    self.training_finished = false
    #save
    block! BotConst::Block_For_Block
  end

  private

  def self.from_omniauth(auth)
    where(uid: auth.uid, is_admin: true).first do |user|
      user.uid = auth.uid
      user.username = auth.username
      user.firstname = auth.first_name
      user.lastname = auth.last_name
      user.photo_url = auth.photo_url
      #user.password = Devise.friendly_token[0,20]
      #session['uid'] = auth.uid
    end
  end

  def email_required?
    false
  end

  def password_required?
    false
  end

  def will_save_change_to_email?
    false
  end

  def log_info
    _info self
  end

  def log_error
    _error self if errors.messages.any?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!  
  before_action :set_user, only: [:show]

  attr_accessor :skip_password_validation

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show; end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
    session[:login] = @user&.uid
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:uid, :username, :firstname, :lastname, :blockeduntil, :locale)
  end

  protected

  def password_required?
    return false
  end
end

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.size, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uid %>
    <%= f.number_field :uid %>
  </div>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class="field">
    <%= f.label :firstname %>
    <%= f.text_field :firstname %>
  </div>

  <div class="field">
    <%= f.label :lastname %>
    <%= f.text_field :lastname %>
  </div>

  <div class="field">
    <%= f.label :blockeduntil %>
    <%= f.datetime_select :blockeduntil %>
  </div>

  <div class="field">
    <%= f.label :locale %>
    <%= f.text_field :locale %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Userid</th>
      <th>Username</th>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Blockeduntil</th>
      <th>Locale</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.uid %></td>
        <td><%= user.username %></td>
        <td><%= user.firstname %></td>
        <td><%= user.lastname %></td>
        <td><%= user.blockeduntil %></td>
        <td><%= user.locale %></td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Userid:</strong>
  <%= @user.uid %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @user.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user.lastname %>
</p>

<p>
  <strong>Blockeduntil:</strong>
  <%= @user.blockeduntil %>
</p>

<p>
  <strong>Locale:</strong>
  <%= @user.locale %>
</p>

<%= link_to 'Back', users_path %>