config/routes.rb
Rails.application.routes.draw do

  telegram_webhook BotRouter

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, :controllers => {
    :omniauth_callbacks => "auth"
  }

  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :signin_path
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :signout_path
  end

  #resources :challenges
  #match '/auth/:provider/callback', :to => 'auth#callback', :via => [:get, :post]

  authenticated :user do
    root 'home#index', as: 'authenticated_root'
  end
  devise_scope :user do
    root 'devise/sessions#new'
  end

  # Wrong route workaround
  match "/404", to: "errors#page_not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  match "*path", to: "errors#page_not_found", via: :all
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TelegramBotApp</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  <nav class="light-blue lighten-1" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="#" class="brand-logo">Chllng</a>
      <ul class="right hide-on-med-and-down">
        <li><% if current_user %>
          <%= link_to "Signout", signout_path_url %>
        <% else %>
          <%= link_to "Signin", signin_path_url %>
        <% end %></li>
      </ul>

      <ul id="nav-mobile" class="sidenav">
        <li><% if current_user %>
          <%= link_to "Signout", signout_path_url %>
        <% else %>
          <%= link_to "Signin", signin_path_url %>
        <% end %></li>
      </ul>
      <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    </div>
  </nav>

  <%- flash.each do |name, msg| -%>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <%- end -%>
  <%= yield %>

  </body>
</html>